### ISSUE TITLE
Remove extra line breaks

### ISSUE THREAD

**Issue by desmondmorris** [ilovevinylrecs/andynystrom#4]
In many of the files, there are multiple line breaks in between statements.  Please keep these to single line breaks.  All files should also end in a single line break as well

![Screen Shot 2020-12-21 at 12 41 15 PM](https://user-images.githubusercontent.com/129360/102805979-0bf3b180-438a-11eb-9781-ab8445bee66f.png)

**Comment by ilovevinylrecs** [comment]
Fixed spacing issues on all files.
